LTO_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
EXTRAKEY_ENABLE = yes
SLEEP_LED_ENABLE = no

BOOTMAGIC_ENABLE = no
RGBLIGHT_ENABLE = no
