LTO_ENABLE = yes

# Some space saving
CONSOLE_ENABLE = no
COMMAND_ENABLE = yes
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

BOOTMAGIC_ENABLE = no
RGBLIGHT_ENABLE = no
